# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtimeIdentifier: [ win-x64, win-x86, linux-x64, linux-arm, linux-arm64, osx-x64, osx-arm64, linux-musl-x64, linux-musl-arm64 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Build MorMor
        shell: powershell
        run: |
          dotnet publish MorMor/MorMor.csproj --self-contained -p:PublishSingleFile=true -p:IncludeContentInSingleFile=true -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net6.0

      - name: Upload binary files(${{ matrix.runtimeIdentifier }}) for .NET 6.0
        uses: actions/upload-artifact@v3
        with:
          name: MorMor_${{ matrix.runtimeIdentifier }}_6.0
          path: MorMor/bin/Debug/net6.0/${{ matrix.runtimeIdentifier }}/publish
          
      - name: Compress files (Not Windows)
        if: matrix.runtimeIdentifier != 'win-x64' && matrix.runtimeIdentifier != 'win-x86'
        run: |
          Compress-Archive -Path 'MorMor\bin\Debug\net6.0\${{ matrix.runtimeIdentifier }}\publish\MorMor' -DestinationPath  'MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip'
      - name: Compress files (Windows)
        if: matrix.runtimeIdentifier == 'win-x64' || matrix.runtimeIdentifier == 'win-x86'
        run: |
          Compress-Archive -Path 'MorMor\bin\Release\net6.0\${{ matrix.runtimeIdentifier }}\publish\MorMor.exe' -DestinationPath  'MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip'
          
      - name: Prepare release files
        uses: actions/upload-artifact@v3
        with:
          name: MorMor_all
          path: MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip
