# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  Build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtimeIdentifier: [ win-x64, win-x86, linux-x64, linux-arm, linux-arm64, osx-x64, osx-arm64, linux-musl-x64, linux-musl-arm64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Build MorMor
        shell: powershell
        run: |
          dotnet build MorMor/MorMor.csproj --self-contained=false -p:PublishSingleFile=false -p:IncludeContentInSingleFile=false -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net6.0

      - name: Upload binary files(${{ matrix.runtimeIdentifier }}) for .NET 6.0
        uses: actions/upload-artifact@v3
        with:
          name: MorMor_${{ matrix.runtimeIdentifier }}_6.0
          path: MorMor/bin/Debug/net6.0/${{ matrix.runtimeIdentifier }}
          
      - name: Compress files (Not Windows)
        if: matrix.runtimeIdentifier != 'win-x64' && matrix.runtimeIdentifier != 'win-x86'
        run: |
          Compress-Archive -Path 'MorMor\bin\Debug\net6.0\${{ matrix.runtimeIdentifier }}\MorMor' -DestinationPath  'MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip'
      - name: Compress files (Windows)
        if: matrix.runtimeIdentifier == 'win-x64' || matrix.runtimeIdentifier == 'win-x86'
        run: |
          Compress-Archive -Path 'MorMor\bin\Debug\net6.0\${{ matrix.runtimeIdentifier }}\MorMor.exe' -DestinationPath  'MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip'
          
      - name: Prepare release files
        uses: actions/upload-artifact@v3
        with:
          name: MorMor_all
          path: MorMor_${{ matrix.runtimeIdentifier }}_6.0.zip
  NightlyRelease:
    name: Nightly Release
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update Nightly Tag
        run: |
          git tag -f nightly
          git push -f origin nightly
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: MorMor_all
          path: ./bin
      - name: Update Nightly Release
        uses: ncipollo/release-action@v1
        with:
          tag: nightly
          name: 'Nightly Release'
          prerelease: true
          body: '> ⚠️This is a nightly release.'
          artifacts: |
            ./bin/*
          allowUpdates: true
          removeArtifacts: true
  
  ClearTempArtifacts:
    name: Clear Temp Artifacts
    if: always()
    runs-on: ubuntu-latest
    needs:
      - NightlyRelease
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            MorMor_all
