name: MomoAPI NuGet Push

on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        run: |
            dotnet build -c Release MomoAPI
            dotnet pack -c Release MomoAPI
            dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg MomoAPI

      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source --username Controllerdestiny --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MomoAPI/index.json"

      - name: Push generated package to NuGet
        run: dotnet nuget push ./MomoAPI/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}
