name: MorMor NuGet Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        run: |
            dotnet build -c Release MorMor
            dotnet pack -c Release MorMor
            dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg MorMor

      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source --username Controllerdestiny --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MorMor/index.json"

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./MorMor/bin/Release/*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.GIT_TOKEN }}

      - name: Push generated package to NuGet
        run: dotnet nuget push ./MorMor/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}
